### ISSUE TITLE
Ability to view more details about grill

### ISSUE THREAD

**Issue by kayla802** [kayla802/GrillBer#18]
Ability to view more details about grill
Brand, Model, City, Cost/Hour, Delivery Cost, Grill Rating, Grill Owner,

**Comment by kayla802** [comment]
**As a User,**

I want to be able to view specific details about individual grills.

**AC:**

When a user clicks on a grill that grill's details are displayed.

**Comment by PercyODI** [comment]
@kayla802 Usually a story also includes a "So that" section. For example:

### Story
As a User,
I want to be able to view specific details about individual grills
So that less data has to be displayed on the table
